
import androidx.compose.ui.graphics.Color

// Light theme
val md_theme_light_primary = Color(0xFF7F4D7A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F6)
val md_theme_light_onPrimaryContainer = Color(0xFF653661)
val md_theme_light_secondary = Color(0xFF6F528A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onSecondaryContainer = Color(0xFF563B71)
val md_theme_light_tertiary = Color(0xFF8F4B3A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD2)
val md_theme_light_onTertiaryContainer = Color(0xFF723425)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFFF7F9)
val md_theme_light_onBackground = Color(0xFF201A1E)
val md_theme_light_surface = Color(0xFFFFF7F9)
val md_theme_light_onSurface = Color(0xFF201A1E)
val md_theme_light_surfaceVariant = Color(0xFFEEDEE7)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)
val md_theme_light_outline = Color(0xFF80747C)
val md_theme_light_outlineVariant = Color(0xFFD1C2CB)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF352E33)
val md_theme_light_inverseOnSurface = Color(0xFFFAEDF4)
val md_theme_light_inversePrimary = Color(0xFFF1B3E7)
// 👇 SurfaceTint can just reuse primary
val md_theme_light_surfaceTint = md_theme_light_primary

// Dark theme
val md_theme_dark_primary = Color(0xFFF1B3E7)
val md_theme_dark_onPrimary = Color(0xFF4C1F49)
val md_theme_dark_primaryContainer = Color(0xFF653661)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F6)
val md_theme_dark_secondary = Color(0xFFDBB9F9)
val md_theme_dark_onSecondary = Color(0xFF3E2458)
val md_theme_dark_secondaryContainer = Color(0xFF563B71)
val md_theme_dark_onSecondaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_tertiary = Color(0xFFFFB4A2)
val md_theme_dark_onTertiary = Color(0xFF561F11)
val md_theme_dark_tertiaryContainer = Color(0xFF723425)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF171216)
val md_theme_dark_onBackground = Color(0xFFEBDFE6)
val md_theme_dark_surface = Color(0xFF171216)
val md_theme_dark_onSurface = Color(0xFFEBDFE6)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C2CB)
val md_theme_dark_outline = Color(0xFF9A8D95)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFEBDFE6)
val md_theme_dark_inverseOnSurface = Color(0xFF352E33)
val md_theme_dark_inversePrimary = Color(0xFF7F4D7A)
val md_theme_dark_surfaceTint = md_theme_dark_primary
